on:
  workflow_call:
    inputs:
      container-image:
        type: string
        required: true
      skip-version:
        type: boolean
        default: false
      skip-install:
        type: boolean
        default: false
      skip-build:
        type: boolean
        default: false
      skip-lint:
        type: boolean
        default: false
      skip-test:
        type: boolean
        default: false
      skip-coverage:
        type: boolean
        default: false
      skip-mutation:
        type: boolean
        default: false
      skip-badge:
        type: boolean
        default: false
    secrets:
      gist-id:
        description: "gist id"
        required: false
      gist-token:
        description: "gist token"
        required: false

jobs:    

  version:
    if: ${{ inputs.skip-version != true }}
    runs-on: ubuntu-latest
    steps:
    - uses: yadickson/actions/version@v1

  install:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-install != true }}
    needs: version
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - uses: yadickson/actions/install@v1

  build:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-build != true }}
    needs: install
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - uses: yadickson/actions/build@v1

  lint:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-lint != true }}
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - uses: yadickson/actions/lint@v1

  test:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-test != true }}
    name: "unit testing"
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - uses: yadickson/actions/test@v1

  coverage:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-coverage != true }}
    name: "coverage report"
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - uses: yadickson/actions/coverage@v1

  mutation:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-mutation != true }}
    name: "mutation testing"
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - name: install procps
      run: apt-get update && apt-get install -y procps
    - uses: yadickson/actions/mutation@v1

  badge:
    if: ${{ always() && !failure() && !cancelled() && inputs.skip-badge != true }}
    needs: [test, coverage, mutation]
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
    - id: project_version
      uses: yadickson/actions/version@v1
    - uses: yadickson/actions/badge@v1
      with:
        version: steps.project_version.outputs.version
        gist-id: ${{ secrets.GIST_ID }}
        gist-token: ${{ secrets.GIST_TOKEN }}
