on:
  workflow_call:
    inputs:
      skip-version:
        type: boolean
        default: false
      skip-install:
        type: boolean
        default: false
      skip-build:
        type: boolean
        default: false
      skip-test:
        type: boolean
        default: false
      skip-coverage:
        type: boolean
        default: false
      skip-mutation:
        type: boolean
        default: false
      skip-badge:
        type: boolean
        default: false
    secrets:
      gist-id:
        description: "gist id"
        required: false
      gist-token:
        description: "gist token"
        required: false

jobs:    

  version:
    name: ${{ inputs.skip-version == false && 'version' || 'DISABLED' }}
    if: ${{ inputs.skip-version != true }}
    runs-on: ubuntu-latest
    steps:
    - uses: yadickson/actions/version@v1

  install:
    if: ${{ inputs.skip-install != true }}
    needs: version
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
    - uses: yadickson/actions/install@v1

  build:
    if: ${{ inputs.skip-build != true }}
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
    - uses: yadickson/actions/build@v1

  test:
    if: ${{ inputs.skip-test != true }}
    name: "unit testing"
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
    - uses: yadickson/actions/test@v1

  coverage:
    if: ${{ inputs.skip-coverage != true }}
    name: "coverage report"
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
    - uses: yadickson/actions/coverage@v1

  mutation:
    if: ${{ inputs.skip-mutation != true }}
    name: "mutation testing"
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
    - uses: yadickson/actions/mutation@v1

  badge:
    if: ${{ inputs.skip-badge != true }}
    needs: [test, coverage, mutation]
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
    - uses: yadickson/actions/badge@v1
      with:
        gist-id: ${{ secrets.GIST_ID }}
        gist-token: ${{ secrets.GIST_TOKEN }}
